baseurl = "http://waffleibot.github.io"
title = "WaffleIBOT"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "WaffleIBOT"
  info = "I'm work on modpacks for minecraft."
  description = "My Website"
  avatarurl = "images/avatar.png"

  faviconSVG = "https://avatars.githubusercontent.com/u/89548916?v=4"
  favicon_32 = "https://avatars.githubusercontent.com/u/89548916?v=4"
  favicon_16 = "https://avatars.githubusercontent.com/u/89548916?v=4"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-3x"
  weight = 1
  url = "https://github.com/WaffleIBOT"
[[params.social]]
  name = "Modrinth"
  icon = "fa fa-wrench fa-3x"
  weight = 2
  url = "https://modrinth.com/user/WaffleIBOT"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-3x"
  weight = 3
  url = "https://twitter.com/WaffleIBOT"


# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"